### ISSUE TITLE
doesnt work under i3

### ISSUE THREAD

**Issue by thelieisajoke** [angelic-sedition/tdrop#1]
the specified terminal wont even open with tdrop, im kind of confused.

this is the output when i press the key.
/usr/bin/tdrop: line 207: type: map_pre: not found
/usr/bin/tdrop: line 220: type: map_post_oneshot: not found
[{"success":true}]
/usr/bin/tdrop: line 238: /tmp/tdrop/auto_hidden/wid: No such file or directory

**Comment by angelic-sedition** [comment]
What's the full command that you've bound a key to? Did you use the `-a` flag (for i3 you should)? It might be a problem with the terminal, so I need to know which one you're trying to use.

**Comment by thelieisajoke** [comment]
I've just tried the proposed command.
tdrop -a -w 1600 -y 14 -s dropdown termite
but it wont work with other terminals either, it just sets the active window to floating mode every 2 invokings.

**Comment by angelic-sedition** [comment]
I will test it. Just to check, do you have tmux installed (without tmux -s will cause a failure)?

**Comment by angelic-sedition** [comment]
I've made changes to prevent the output you originally posted from occurring (it's not relevant to the problem and would happen even if tdrop was successful). I've also made it so that the active window won't be floated in i3 in the case that a window is not created.

Currently tdrop is working fine for me in i3. Let me know if my previous suggestion isn't the issue.

**Comment by thelieisajoke** [comment]
really fine of you.
can something be done against the flickering in i3, too?

**Comment by angelic-sedition** [comment]
If i3 implemented one-time rules (so that you could add a rule to float a window of a certain class only the next time it was opened instead of every time), the flicker could probably be dealt with. If you're willing to to have every window of the class of terminal you're using floated (maybe you only use it for a dropdown), adding something like `for_window [class="Termite"] floating enable` reduces the flicker.

Also, if you use (even short) fade-in  with a compositor (e.g. compton), flicker probably won't be noticeable at all, so neither of the above will be necessary.
