### ISSUE TITLE
Cinnamon, window position

### ISSUE THREAD

**Issue by zhdali** [angelic-sedition/tdrop#2]
Hi, very good job. I hope to not get wrong.
I'm using arch/cinnamon.
When mapping then unmapping, the window go always at the center of the screen (except first time, when the window is created).

I use these commands:
tdrop urxvt and tdrop current 
I have also tried tdrop -a
Can the Muffin window manager be added to the supported window managers?

**Comment by angelic-sedition** [comment]
Cinnamon always crashes for me which is why I never added support for muffin. It may be simple to get working though.

Can you give me the output of running `xprop -notype -id "$(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" -f _NET_WM_NAME 8u | awk -F "\"" '/WM_NAME/ {print $2}' | head -n 1`?

**Comment by zhdali** [comment]
Hi, i see your mail this morning.
The output is:
Mutter (Muffin)



----Messaggio originale----

Da: notifications@github.com

Data: 11-ago-2015 3.22

A: "angelic-sedition/tdrop"<tdrop@noreply.github.com>

Cc: "zhdali"<zhdali@tin.it>

Ogg: Re: [tdrop] Cinnamon, window position (#2)




Cinnamon always crashes for me which is why I never added support for muffin. It may be simple to get working though.


Can you give me the output of running xprop -notype -id "$(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" -f _NET_WM_NAME 8u | awk -F "\"" '/WM_NAME/ {print $2}' | head -n 1?

**Comment by angelic-sedition** [comment]
Tell me if the most recent version fixes the problem.

**Comment by zhdali** [comment]
Sorry for the delay.
Yes, it almost solves the problem.
The window continues to appear always in the middle of the screen
but now it is moved always in the correct position.
Is there a way to make the window appear in the correct position?

**Comment by angelic-sedition** [comment]
Is it immediately moved (quickly jerks into the right position)? The reason this happens is that for Muffin, when remapping a window, the previous position is not maintained, so the window has to be moved.

I think I can fix this problem completely, but I need to think about the best way to do it (since always moving the window may not be desirable if it's not necessary). I'm a bit busy right now, but when I have the time I'll try to fix this visual annoyance. 

For a temporary fix see [this](https://github.com/angelic-sedition/tdrop#flicker). I'm closing this issue; see #4 for progress on the problem of the window first appearing in the middle.

**Comment by angelic-sedition** [comment]
I've gotten cinnamon working. For me, this most recent commit prevents the visual annoyance you mentioned. Let me know if you have any problems.
